{% set name = "eo-learn-visualization" %}
{% set version = "1.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5f633e4627674665695439e3827ef6db66795935e4dbf774a248cc6429f358d1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - eo-learn-core
    - python-graphviz
    - jinja2
    - matplotlib-base
    - pydot
    - pygments
    - python >=3.5
    - geoviews
    - hvplot
    - pyepsg
    - xarray
test:
  imports:
    - eolearn
    - eolearn.visualization
  requires:
    - python-graphviz
    - eo-learn-core
about:
  home: https://github.com/sentinel-hub/eo-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of visualization utilities
  doc_url: https://eo-learn.readthedocs.io/en/latest/eolearn.visualization.html
  dev_url: https://github.com/sentinel-hub/eo-learn

extra:
  recipe-maintainers:
    - mxr-conda
